apiVersion: app/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    app.kubernetes.io/managed-by: kargocd
  name: krampoline
  namespace: default
spec:
  rules:
    
http:
      paths:
backend:
          serviceName: krampoline
          servicePort: 80
          path: /
          pathType: Prefix