namespace: default
resources:https://www.notion.so/dcee9c1adff04580a2ddbe0847f888ab?v=c383797737a443a685fa1727fa341baa
    - nginx.yaml
    - mariadb.yaml
    - backend.yaml
configMapGenerator:
    - name: nginx
      files:
          - configs/default.conf
    - name: init-db
      files:
          - configs/init.sql
